version: "3.4"

services:
  app:
    build:
      context: .
      target: app
    volumes:
      - .:/app/
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:8080:8080"
    command: bash -c "npm start"